import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, Hammer, HandCoins, House } from "lucide-react";
import PageHero from "@/components/PageHero";
import CTASection from "@/components/CTASection";

export const metadata: Metadata = { title: "Services", description: "Explore K A CAPITAL services in buying and selling, property development and resale, house renovation and improvement, and microfinance." };
const services = [
  { number: "01", icon: House, title: "Buying & Selling", image: "/images/buying-selling.png", alt: "Property sale agreement and professional handshake", text: "Reliable buying and selling services built around transparent transactions, practical guidance and valuable opportunities. We focus on clear communication throughout the process and on understanding what our customers are looking to achieve." },
  { number: "02", icon: Building2, title: "Property Development & Resale", image: "/images/property-development.png", alt: "Property development team reviewing a house under construction", text: "We identify properties with potential, improve them to a higher standard and prepare them for stronger resale value. Our considered approach connects property potential with purposeful improvements and professional presentation." },
  { number: "03", icon: Hammer, title: "House Renovation & Improvement", image: "/images/renovation.png", alt: "Modern home interior undergoing a professional renovation", text: "Thoughtful renovations, upgrades and enhancements designed to improve comfort, functionality and property value. Each improvement is approached with attention to customer needs, quality and the character of the property." },
  { number: "04", icon: HandCoins, title: "Microfinance", image: "/images/microfinance.png", alt: "Professional discussing finance solutions with a customer", text: "Microfinance-related services intended to support individuals and small businesses with access to financial opportunities. We approach every enquiry responsibly, with customer focus and clear communication." },
];
export default function ServicesPage() { return <main id="main-content"><PageHero eyebrow="Our Services" title="Solutions Built Around Value" image="/images/hero-property.png" /><section className="section service-features"><div className="shell"><div className="section-heading compact"><div><p className="eyebrow">Focused Expertise</p><h2>Four connected areas of business.</h2></div><p>Each service is guided by trust, quality and a professional approach from the first conversation onward.</p></div><div className="feature-list">{services.map(({ number, icon: Icon, title, image, alt, text }, index) => <article className={`service-feature${index % 2 ? " is-reversed" : ""}`} key={title}><div className="feature-image"><Image src={image} alt={alt} fill sizes="(max-width: 800px) 100vw, 50vw" /><span>{number}</span></div><div className="feature-copy"><div className="value-icon"><Icon aria-hidden="true" /></div><p className="eyebrow">Service {number}</p><h2>{title}</h2><p>{text}</p><Link className="text-link" href="/contact">Enquire about this service <ArrowRight size={16} aria-hidden="true" /></Link></div></article>)}</div></div></section><CTASection /></main>; }
